import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "../styles/globals.css";
import ReduxProvider from "@/redux/provider/provider";

const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={mulish.className}>
                <ReduxProvider>{children}</ReduxProvider>
            </body>
        </html>
    );
}
